Steel trade review debugged
pik-piam/simson pull request #14
Opened 2024-10-31 16:20 UTC by Merjo

Thanks for your review @JakobBD  - I looked at most of it now, all looks fine to me for now, I just made a couple of small changes. Solved your problem by creating a subclass of Extrapolation OneDimensional Extrapolation  and made the non-WeightedProportionalExtrapolations inherit from that, and only those require the one dimension for now. Not sure if that's a bad coding standard, feel free to change it again, it's just good for me for now so that I can go ahead with the trade module.

I added some small changes especially to the trade implementation to debug it.

2024-11-01 14:14 UTC, JakobBD requested changes
Thanks for debugging! Looks great! 
I added a few really minor comments. 
If you like, you can address them only after reworking the trade module, as you prefer.

2024-11-01 14:14 UTC, JakobBD commented on simson/common/data_extrapolations.py
> +            "data_to_extrapolate must be smaller then target_range")
Last check should be moved to Extrapolation parent class. 
The function name in parent and subclass should then be different, such that inheriting just adds a second validator-decorated function.

2024-11-01 14:14 UTC, JakobBD commented on simson/common/data_extrapolations.py
> +    def validate_data(self):
this should get some additional checks on the shape of the input arrays, I suppose?

2024-11-01 14:14 UTC, JakobBD commented on simson/steel/steel_model.py
> +                                            else prm.dims.replace('h', self.dims['t']))
Maybe initialize `future_trade` as an empty dict and make this a loop with several lines. Seems a bit too long for a comprehension now...

2024-11-01 17:29 UTC, Merjo commented
@JakobBD @SallyDa So I just committed the first version of the trade module and adapted the code with the suggestions above. Also added a pytest for the get shares over NDArray functionality and implemented the trade balancing. I could quite imagine that you guys would like to change the structure around a bit - this is how it felt natural to me but am very happy with any changes. This code should work in collaboration with the now updated nda_shares sodym branch. Hope you guys have a nice weekend!

2024-11-06 13:15 UTC, SallyDa approved these changes

2024-11-06 13:16 UTC, merged